@startuml projectMap
skinparam componentStyle uml2

:Usuario:

package "ProjectMap" {
  package "Frontend" {
    [React App]
}

cloud {
    database MongoDB {
        [Collections]
    }
}

package "Backend" {
    [Nest.js Server]
}

:Usuario: ---> [React App] : Interacción con el sitio web
[React App] ---> [Nest.js Server] : HTTP
[Nest.js Server] ---> [Collections] : Queries a MongoDB
}
@enduml