@startuml
skinparam backgroundColor #FEFECE
skinparam componentStyle uml2

actor User as Actor
package "React Frontend" {
    [React App]
}

cloud {
    database MongoDBAtlas {
        [Collections]
    }
}

package "Nest.js Backend" {
    [Nest.js Server]
}

Actor --> [React App] : Interacts with UI
[React App] --> [Nest.js Server] : HTTP Requests
[Nest.js Server] --> [Collections] : MongoDB Queries

@enduml

